gui:
  theme:
    activeBorderColor:
      - '#b4befe' # Lavender
      - bold
    inactiveBorderColor:
      - '#a6adc8' # Subtext0
    optionsTextColor:
      - '#89b4fa' # Blue
    selectedLineBgColor:
      - '#313244' # Surface1
    selectedRangeBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a' # Surface2
    cherryPickedCommitTextStyle:
      - '#a6e3a1' # Green
    markedBaseCommitTextStyle:
      - '#fab387' # Peach
    unstagedChangesColor:
      - '#f38ba8' # Red
    defaultTextColor:
      - '#cdd6f4' # Text
git:
  autoFetch: false
  pagers:
    - colorArg: always
      pager: delta --dark --side-by-side --paging=never
customCommands:
  - key: '<c-t>'
    context: 'commits'
    description: 'Diff Options Menu'
    prompts:
      - type: 'menu'
        title: 'Choose Diff Target'
        key: 'DiffChoice'
        options:
          - name: 'Diff with previous commit'
            value: 'git difftool -d {{.SelectedLocalCommit.Sha}}~1 {{.SelectedLocalCommit.Sha}}'
          - name: 'Diff with working tree'
            value: 'git difftool -d {{.SelectedLocalCommit.Sha}}'
    # The selected option's value gets populated into the Form context variable below
    command: '{{.Form.DiffChoice}}'
    output: terminal
