[[mgr.prepend_keymap]]
on = [ "<Enter>" ]
run = "enter"
desc = "Enter directory"

[[mgr.prepend_keymap]]
on = [ "1" ]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "2" ]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "3" ]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "4" ]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "5" ]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "6" ]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "7" ]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "8" ]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "9" ]
run = "plugin relative-motions 9"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = [ "t", "1" ]
run = "tab_switch 0"
desc = "Switch to tab 1"

[[mgr.prepend_keymap]]
on = [ "t", "2" ]
run = "tab_switch 1"
desc = "Switch to tab 2"

[[mgr.prepend_keymap]]
on = [ "t", "3" ]
run = "tab_switch 2"
desc = "Switch to tab 3"

[[mgr.prepend_keymap]]
on = [ "t", "4" ]
run = "tab_switch 3"
desc = "Switch to tab 4"

[[mgr.prepend_keymap]]
on = [ "t", "5" ]
run = "tab_switch 4"
desc = "Switch to tab 5"

[[mgr.prepend_keymap]]
on = [ "t", "6" ]
run = "tab_switch 5"
desc = "Switch to tab 6"

[[mgr.prepend_keymap]]
on = [ "t", "7" ]
run = "tab_switch 6"
desc = "Switch to tab 7"

[[mgr.prepend_keymap]]
on = [ "t", "8" ]
run = "tab_switch 7"
desc = "Switch to tab 8"

[[mgr.prepend_keymap]]
on = [ "t", "9" ]
run = "tab_switch 8"
desc = "Switch to tab 9"
